import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/Wrraper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
